name: My First Workflow
on: workflow_dispatch
jobs:
  first_job:
  runs-on: ubuntu-latest
  steps:
    - name: Print Greatings
      runs: echo "Hello World!" 
    - name: Print Goodbye
      runs: echo "Goodbye"
      